# Pass unsigned dtbo image (generated by build/tasks/dtimages.mk) to Android
# build system for AVB signing
DTBO_UNSIGNED := dtbo-unsigned.img
# $(PRODUCT_OUT) hasn't been defined yet, so use "=" instead of ":="
# so that it is resolved later
BOARD_PREBUILT_DTBOIMAGE = $(PRODUCT_OUT)/$(DTBO_UNSIGNED)

# Modules in the rootfs
BOARD_VENDOR_KERNEL_MODULES := $(wildcard $(TARGET_PREBUILT_KERNEL_DIR)/*.ko)
ifneq ($(BOARD_VENDOR_KERNEL_MODULES),)

BOARD_VENDOR_RAMDISK_KERNEL_MODULES += \
  $(TARGET_PREBUILT_KERNEL_DIR)/axg.ko \
  $(TARGET_PREBUILT_KERNEL_DIR)/axg-audio.ko \
  $(TARGET_PREBUILT_KERNEL_DIR)/axg-aoclk.ko \
  $(TARGET_PREBUILT_KERNEL_DIR)/clk-cpu-dyndiv.ko \
  $(TARGET_PREBUILT_KERNEL_DIR)/clk-regmap.ko \
  $(TARGET_PREBUILT_KERNEL_DIR)/clk-phase.ko \
  $(TARGET_PREBUILT_KERNEL_DIR)/gxbb-aoclk.ko \
  $(TARGET_PREBUILT_KERNEL_DIR)/clk-dualdiv.ko \
  $(TARGET_PREBUILT_KERNEL_DIR)/clk-pll.ko \
  $(TARGET_PREBUILT_KERNEL_DIR)/clk-mpll.ko \
  $(TARGET_PREBUILT_KERNEL_DIR)/meson-eeclk.ko \
  $(TARGET_PREBUILT_KERNEL_DIR)/sclk-div.ko \
  $(TARGET_PREBUILT_KERNEL_DIR)/g12a-aoclk.ko \
  $(TARGET_PREBUILT_KERNEL_DIR)/g12a.ko \
  $(TARGET_PREBUILT_KERNEL_DIR)/meson-aoclk.ko \
  $(TARGET_PREBUILT_KERNEL_DIR)/vid-pll-div.ko \
  $(TARGET_PREBUILT_KERNEL_DIR)/gxbb.ko \
  $(TARGET_PREBUILT_KERNEL_DIR)/pinctrl-meson-a1.ko \
  $(TARGET_PREBUILT_KERNEL_DIR)/pinctrl-meson-axg-pmx.ko \
  $(TARGET_PREBUILT_KERNEL_DIR)/pinctrl-meson-g12a.ko \
  $(TARGET_PREBUILT_KERNEL_DIR)/pinctrl-meson-axg.ko \
  $(TARGET_PREBUILT_KERNEL_DIR)/pinctrl-meson-gxl.ko \
  $(TARGET_PREBUILT_KERNEL_DIR)/pinctrl-meson.ko \
  $(TARGET_PREBUILT_KERNEL_DIR)/pinctrl-meson-gxbb.ko \
  $(TARGET_PREBUILT_KERNEL_DIR)/pinctrl-meson8-pmx.ko \
  $(TARGET_PREBUILT_KERNEL_DIR)/reset-meson.ko \
  $(TARGET_PREBUILT_KERNEL_DIR)/reset-meson-audio-arb.ko \
  $(TARGET_PREBUILT_KERNEL_DIR)/meson-ee-pwrc.ko \
  $(TARGET_PREBUILT_KERNEL_DIR)/pwm-meson.ko \
  $(TARGET_PREBUILT_KERNEL_DIR)/pwm-regulator.ko \
  $(TARGET_PREBUILT_KERNEL_DIR)/meson-gx-mmc.ko \
  $(TARGET_PREBUILT_KERNEL_DIR)/pwrseq_simple.ko \
  $(TARGET_PREBUILT_KERNEL_DIR)/pwrseq_emmc.ko

# SD/eMMC G12/SM1 specific
BOARD_VENDOR_RAMDISK_KERNEL_MODULES_LOAD += \
  $(TARGET_PREBUILT_KERNEL_DIR)/g12a_aoclk.ko \
  $(TARGET_PREBUILT_KERNEL_DIR)/g12a.ko \
  $(TARGET_PREBUILT_KERNEL_DIR)/meson-eeclk.ko \
  $(TARGET_PREBUILT_KERNEL_DIR)/pinctrl-meson-g12a.ko \
  $(TARGET_PREBUILT_KERNEL_DIR)/reset-meson.ko \
  $(TARGET_PREBUILT_KERNEL_DIR)/pwm-meson.ko \
  $(TARGET_PREBUILT_KERNEL_DIR)/pwrseq_simple.ko \
  $(TARGET_PREBUILT_KERNEL_DIR)/pwrseq_emmc.ko \
  $(TARGET_PREBUILT_KERNEL_DIR)/meson-gx-mmc.ko

# Serial console (may be built-in, so check if present)
UART_MOD=$(TARGET_PREBUILT_KERNEL_DIR)/meson_uart.ko
ifneq (,$(wildcard $(UART_MOD)))
BOARD_VENDOR_RAMDISK_KERNEL_MODULES += $(UART_MOD)
BOARD_VENDOR_RAMDISK_KERNEL_MODULES_LOAD += $(UART_MOD)
endif

endif

ifneq ($(TARGET_KERNEL_USE), 4.19)
DEVICE_MANIFEST_FILE += device/amlogic/yukawa/manifest_kernel5.xml
endif
