ifneq ($(TARGET_KERNEL_VERSION),)
TARGET_KERNEL_USE := $(TARGET_KERNEL_VERSION)
endif
TARGET_KERNEL_USE ?= 5.10

TARGET_PREBUILT_KERNEL_DIR ?= device/amlogic/yukawa-kernel/$(TARGET_KERNEL_USE)
TARGET_PREBUILT_KERNEL ?= $(TARGET_PREBUILT_KERNEL_DIR)/Image.lz4
LOCAL_DTB ?= $(TARGET_PREBUILT_KERNEL_DIR)

PRODUCT_COPY_FILES += \
  $(TARGET_PREBUILT_KERNEL):kernel
