system				/system		ext4	noatime,ro,errors=panic						wait,slotselect,logical,first_stage_mount
vendor				/vendor		ext4	noatime,ro,errors=panic						wait,slotselect,logical,first_stage_mount
/dev/block/by-name/metadata	/metadata	ext4	noatime,nosuid,nodev,discard,sync	wait,check,formattable,first_stage_mount
/dev/block/by-name/userdata	/data		f2fs	noatime,nosuid,nodev,inlinecrypt,reserve_root=32768	latemount,wait,check,fileencryption=software,quota,formattable,fscompress,readahead_size_kb=128,checkpoint=fs
/dev/block/by-name/misc		/misc		emmc	defaults							defaults
*/block/mmcblk0			auto		auto	defaults							voldmanaged=sdcard1:auto,encryptable=userdata
*/block/sd*			auto		auto	defaults							voldmanaged=usb:auto,noemulatedsd
/dev/block/zram0		none		swap	defaults							zramsize=268435456
